name: flutter_club
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.15.1
  firebase_ai: ^2.2.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  flutter_bloc: ^9.1.1
  google_sign_in: ^6.2.1
  email_otp: ^3.0.2
  easy_date_timeline: ^2.0.9
  intl: ^0.20.2
  another_flushbar: ^1.12.32
  flutter_slidable: ^4.0.1
  restart_app: ^1.3.2
  google_nav_bar: ^5.0.7
  glass_kit: ^4.0.1
  flutter_html: ^3.0.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.3.2
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # 👈 goes here under dev_dependencies

flutter_icons: # 👈 separate root-level config
  android: true
  ios: true
  image_path: "lib/showcase_project/images/adobe_edit.png"

flutter:
  uses-material-design: true
  assets:
    - lib/Levelup/images/
    - lib/Levelup/images/applelogo2.png
