// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEzW-iKnI_WsHMnJ181J_RjNk_2dfIBs',
    appId: '1:118716581628:web:26f0f47e222009421e3979',
    messagingSenderId: '118716581628',
    projectId: 'flutterclub-a1731',
    authDomain: 'flutterclub-a1731.firebaseapp.com',
    storageBucket: 'flutterclub-a1731.firebasestorage.app',
    measurementId: 'G-JM86J0JBEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fijzvx6Z4U5knvlRUOPdGa46wJTJ-LA',
    appId: '1:118716581628:android:5d937ffcecc76fa21e3979',
    messagingSenderId: '118716581628',
    projectId: 'flutterclub-a1731',
    storageBucket: 'flutterclub-a1731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLsdzt-H7AHzP_ImMXO0jnOtY8F8W_1Vs',
    appId: '1:118716581628:ios:7f53db3f09f4c5111e3979',
    messagingSenderId: '118716581628',
    projectId: 'flutterclub-a1731',
    storageBucket: 'flutterclub-a1731.firebasestorage.app',
    iosClientId: '118716581628-ltlro51m2e2e44fbmfgstic33ifnk0r4.apps.googleusercontent.com',
    iosBundleId: 'com.levelup.ahs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLsdzt-H7AHzP_ImMXO0jnOtY8F8W_1Vs',
    appId: '1:118716581628:ios:0edceb9fa11d0f661e3979',
    messagingSenderId: '118716581628',
    projectId: 'flutterclub-a1731',
    storageBucket: 'flutterclub-a1731.firebasestorage.app',
    iosClientId: '118716581628-d0kc52he5ru9lo6081qv7rijv3cqj0ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvEzW-iKnI_WsHMnJ181J_RjNk_2dfIBs',
    appId: '1:118716581628:web:b9f152c2bcb349701e3979',
    messagingSenderId: '118716581628',
    projectId: 'flutterclub-a1731',
    authDomain: 'flutterclub-a1731.firebaseapp.com',
    storageBucket: 'flutterclub-a1731.firebasestorage.app',
    measurementId: 'G-2WXRLY8NLX',
  );

}